### ISSUE TITLE
Unable to use doct with `add-to-list`

### ISSUE THREAD

**Issue by wagk** [progfolio/doct#11]
Hello; Thanks for implementing this macro (It's been fairly useful)

My current Emacs workflow involves me defining and adding capture templates from multiple files, and as such I would like to be able to to use `add-to-list` instead of `setq`:

```elisp
(add-to-list 'org-capture-templates
      (doct `(("Note"
               :keys "n"
               :file ,my-notes-file
               :type entry
               :template ("* %^{DESCRIPTION} %^g"
                          ":PROPERTIES:"
                          ":CREATED: %U"
                          ":END:"
                          "%?")))))
```

However `doct` seems to return a list of lists, which (as far as I can tell) makes it unable to integrate with existing `org-capture-template` entries.

Passing `doct` a single list generates a `Wrong type argument: listp` error, and I'm not sure if manually extracting it from the list would break something.

I would like to be able to incrementally call `doct` and add capture templates as needed, instead of having to define it all in a single call. Is that possible?

**Comment by progfolio** [comment]
Thank you for using doct!

> ...doct seems to return a list of lists, which (as far as I can tell) makes it unable to integrate with existing org-capture-template entries.
Passing doct a single list generates a Wrong type argument: listp error, and I'm not sure if manually extracting it from the list would break something.

I'd write a function that takes care of wrapping a single declaration in a list and unwrapping the result:

```emacs-lisp
(defun my/add-doct-to-capture-templates (declaration &optional append compare-fn)
  "Add a single DECLARATION to `org-capture-templates'.
APPEND and COMPARE-FN are passed to `add-to-list'."
  (add-to-list 'org-capture-templates (car (doct `(,declaration)))
               append compare-fn))

(let ((org-capture-templates '(("p" "Pre-existing template" entry (file "")))))
  (my/add-doct-to-capture-templates
   '("testing function" :keys "f" :file ""))
  (org-capture))
```
doct returns a list of templates, so altering that list should not break anything unless it is turned into a value that org-capture-templates wouldn't normally accept.

Does that help?

**Comment by wagk** [comment]
Yes, `(car (doct ...))` looks like it will handle my use case.

Would this affect the bundling of parent and child commands?

**Comment by progfolio** [comment]
I'm not sure I understand the question. Could you provide a minimal example that illustrates it?

**Comment by progfolio** [comment]
If I understand correctly:
Your concern is whether you can use the `:children` keyword
while using add-to-list to modify org-capture-templates?

In that case we can't just take the car of the resultant list because
a single declaration may convert to multiple templates.
Something like this would work better:

```emacs-lisp
    (defun my/doct-add-to-templates (declarations &optional append)
      "Add DECLARATIONS to front of `org-capture-templates'.
    If APPEND is non-nil add to back of `org-capture-templates'."
      (let* ((declarations (if (seq-every-p #'listp declarations)
                               declarations
                             `(,declarations)))
             (args `(,(doct declarations)
                     ,org-capture-templates)))
        (setq org-capture-templates
              (apply #'append (if append (nreverse args) args)))))
```

Example usage:
```emacs-lisp
    (let ((org-capture-templates '()))
      ;;works with a list of declarations
      (my/doct-add-to-templates '((:group
                                   :file ""
                                   :children
                                   (("A" :keys "a"
                                     :children (("1" :keys "1")
                                                ("2" :keys "2")))
                                    ("B" :keys "b"
                                     :children (("1" :keys "1")
                                                ("2" :keys "2")))))))
    
      ;;Later on in your init, you can add more.
      ;;A single declaration:
      (my/doct-add-to-templates '("C" :keys "c" :file ""))
    
      ;;And even later, a declaration added to the end of org-capture-templates:
      (my/doct-add-to-templates '("D" :keys "d" :file ""
                                  :children (("1" :keys "1")
                                             ("2" :keys "2")
                                             ("3" :keys "3")))
                                t)
      (org-capture))
```

Results in a list of templates that preserves the parent/child relationship of each declaration and is ordered:

    Select a capture template
    ===========================
    
    [c]      C
    [a]...   A...
    [b]...   B...
    [d]...   D...

These is more flexible than just popping the car of the list and allows adding to `org-capture-templates` with multiple calls.

Perhaps I should allow `doct` to accept a single declaration as an argument.
I do allow this with some declaration keywords (`:children` and `:context)`.
But in either case `doct` must return a list of templates.

**Comment by progfolio** [comment]
I've modified `doct` so it accepts a single declaration as well as a list of declarations.
Doing so simplifies the implementation of that function I suggested a bit. This should work on latest master:

```emacs-lisp
(defun my/doct-add-to-templates (declarations &optional append)
  "Add converted DECLARATIONS to front of `org-capture-templates'.
If APPEND is non-nil add to back of `org-capture-templates'."
  (let ((args `(,(doct declarations) ,org-capture-templates)))
    (setq org-capture-templates
          (apply #'append (if append (nreverse args) args)))))
```
Does that address the question you had?

**Comment by progfolio** [comment]
I'm going to consider this taken care of.  Feel free to comment on this issue or start a new one if the above does not address your question.

**Comment by philipsd6** [comment]
@progfolio, perhaps you would consider adding `doct-add-to-templates` and/or documenting this in the installation/setup docs? I build up my init as an org file, so several sections update the capture templates, and I spent a fair amount of time trying to get this working before I found this closed issue.

**Comment by progfolio** [comment]
@philipsd6 I've added a function that should accommodate your use case:

 https://github.com/progfolio/doct#doct-add-to
 
 Note this is slightly different form `add-to-list`. It does not mutate the original list and should work properly with lexical variables.

**Comment by philipsd6** [comment]
Oh thanks! I'll check that out with my setup.
