### ISSUE TITLE
org-roam integration

### ISSUE THREAD

**Issue by ironicbadger** [progfolio/doct#16]
Very new to emacs (doom) and am using org-roam plus doct.

```
# desired filename output
20200520231937-storage.org

# generated successfully without doct with
:file-name "%(format-time-string \"%Y-%m-%d--%H-%M-%SZ--${slug}\" (current-time) t)"
```

I've attempted a few ways to achieve the desired effect however I must be missing something

```
 (use-package! org-roam
  :hook
  (after-init . org-roam-mode)
  :config
  (setq org-roam-capture-templates
        (doct '(("New SSH Episode" :keys "e"
                     :file "~/Nextcloud/org/personal/ssh/"
                     ;:file (lambda() (concat (format-time-string "%Y-%m-%d--%H-%M-%SZ--${slug}") (current-time) ".org"))
                     ;:file-name "~/Nextcloud/org/personal/ssh/"
                     ;:file-name "~/Nextcloud/org/personal/ssh/%(format-time-string \"%Y-%m-%d--%H-%M-%SZ--${slug}\" (current-time) t)"
                     :function org-roam--capture-get-point
                     :type plain
                     :template "#+ROAM_ALIAS: \"SSH Episode %^{PROMPT|Episode Number (short)?|}\"
#+AIRDATE: %^{PROMPT|Air Date? (yyyy-mm-dd)|2020-|}
#+EPISODE_URL: https://selfhosted.show/%\\1
#+EPISODE_TITLE: %^{PROMPT|Episode Title?|}

* Fireside Episode Description: %?")))))
```

All of the above options return a filename that looks like this

```
20200525235930.org
```

As per the first code block I would love the "slug" to be in the actual filename rather than just an ambiguous date. So I must be missing something really simple and would really appreciate some assistance here. Thanks!

**Comment by progfolio** [comment]
EDIT: please see superseding gist:

https://gist.github.com/progfolio/2871f12099be3913a1c61a3c3062f4fd


Unfortunately, `org-roam` does not integrate with `doct` well yet.
As a workaround you could define a function which takes a custom keyword on the declaration,
converts everything as doct usually would, and then places the keywords that org-roam expects on the resultant template:

This is the function (note this is missing some corner cases):

```emacs-lisp
    (defun +doct-org-roam (groups)
      (let (converted)
        (dolist (group groups)
          (let* ((props (nthcdr (if (= (length group) 4) 2 5) group)))
                 (roam-properties (plist-get (plist-get props :doct) :org-roam)))
            (push `(,@group ,@roam-properties) converted)))
        (setq doct-templates (nreverse converted))))
```

Then you would need to tell `doct` to apply this function to the converted declarations:
```emacs-lisp
    (setq doct-after-conversion-functions '(+doct-org-roam))
```

And you could declare your \`org-roam-capture-templates\` like so:

```emacs-lisp
    (setq org-roam-capture-templates
          (doct '(("default" :keys "d"
                   :type plain
                   :function org-roam-capture--get-point
                   :template "%?"
                   :unnarrowed t
                   ;;org-roam specific keywords go in this plist
                   ;;e.g. :file-name and :head
                   :org-roam (:file-name "%(format-time-string \"%Y-%m-%d--%H-%M-%SZ--${slug}\" (current-time) t)")))))
```

Again, this is not a tested implementation and would likely need tweaking for anything outside of simple declarations.

**Comment by ironicbadger** [comment]
Thank you very much for this code! I just got chance to test it and it works well for my needs I think. So until 'real support' this will do nicely, thanks.

**Comment by spacekitteh** [comment]
This (= the gist) doesn't seem to work with org-roam v2 templates. Any idea how to fix it?

E.g. from this:
```elisp
("Plain note"
		:keys "p"
		:type plain 
		:function org-roam-capture--get-point
		:template     ":THOUGHTS:\n:END:\n%i%?"
		:org-roam
		( :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}"
					 "#+title: ${title}\n#+FILETAGS: :WIP:needs_tags:\n")
		  :unnarrowed t ))
														)
```
I get this:

```elisp
((#2="p" #1="Plain note" plain #'org-roam-capture--get-point #3=":THOUGHTS:
:END:
%i%?" :doct
(:doct-name #1# :keys #2# :type plain :function org-roam-capture--get-point :template #3# :org-roam
			(:if-new
			 (file+head #4="%<%Y%m%d%H%M%S>-${slug}" #5="#+title: ${title}
#+FILETAGS: :WIP:needs_tags:
")
			 :unnarrowed t)
			:doct-custom
			(:org-roam
			 (:if-new
			  (file+head #4# #5#)
			  :unnarrowed t)))
:if-new
(file+head #4# #5#)
:unnarrowed t))
```

**Comment by progfolio** [comment]
Sorry, even when I wrote that original code I had moved on from Org-roam.
I took a brief look to see what had changed design-wise with v2, but I don't have any time to dedicate to this now. Feel free to modify any of the code here to suit your needs if you figure it out.

**Comment by spacekitteh** [comment]
Fair enough!

**Comment by spacekitteh** [comment]
Can you explain this line?
```elisp
((props (nthcdr (if (= (length template) 4) 2 5) template))
```
More specifically, the numbers --- what do they correspond to?

**Comment by progfolio** [comment]
> Can you explain this line?

Sure. At the point `doct-after-conversion-functions` are run, each
template still has all of its metadata.
If the template is a parent and has properties, it will be of the form:

```emacs-lisp
(let ((example '(KEY DESCRIPTION PROPERTIES)))
  (nthcdr 2 example)) ;=> (PROPERTIES)
```


If it is a child with properties it will be of the form:

```emacs-lisp
(let ((example '(KEY DESCRIPTION TYPE TARGET TEMPLATE PROPERTIES)))
  (nthcdr 5 example)) ;=> (PROPERTIES)
```

So that line in particular is grabbing the template's properties in either case.
It then examines it for doct's property list (:doct) and an :org-roam property list in that.
If it finds those, it will move all the values in the :org-roam plist to the top-level of the template.
This is where they were expected to be as far as org-roam v1 goes.
I do not know if this has changed or any particular keywords it used in templating have. 

If you could provide a specific error or describe what happens when you tried this with v2 I may be able to point you in a more specific direction.

**Comment by spacekitteh** [comment]
Ok nevermind the above. If I edit the processed template above to remove the `#'org-roam-capture--get-point`, then it works. However, doct demands the existence of either `:function` or a `:file` property.

**Comment by progfolio** [comment]
Could you share the actual error message, please?

**Comment by progfolio** [comment]
Nevermind. I've taken a closer look at org-roam v2.
It looks like `org-roam-capture-templates` does not allow for a custom placement function or file.
Take a look at `org-roam-capture--convert-template` which hardcodes `org-roam-capture--get-point` as the function to determine the target:


```emacs-lisp
(defun org-roam-capture--convert-template (template &optional props)
  "Convert TEMPLATE from Org-roam syntax to `org-capture-templates' syntax.
PROPS is a plist containing additional Org-roam specific
properties to be added to the template."
  (pcase template
    (`(,_key ,_desc) template)
    (`(,key ,desc ,type ,body . ,rest)
     (setq rest (append rest props))
     (let (org-roam-plist options)
       (while rest
         (let* ((key (pop rest))
                (val (pop rest))
                (custom (member key org-roam-capture--template-keywords)))
           (when (and custom
                      (not val))
             (user-error "Invalid capture template format: %s\nkey %s cannot be nil" template key))
           (if custom
               (setq org-roam-plist (plist-put org-roam-plist key val))
             (setq options (plist-put options key val)))))
       (append `(,key ,desc ,type #'org-roam-capture--get-point ,body)
               options
               (list :org-roam org-roam-plist))))
    (_ (signal 'invalid-template template))))
```

I understand why Jethro chose this design, but it violates the shape of a valid capture-template, so doct will throw an error. You should be able to specify a dummy :function to satisfy doct and it will still be ignored by `org-roam-capture--convert-template`. e.g.

```emacs-lisp
(doct '(("example"
         :keys "e"
         :type plain
         :template "%?"
         :function ignore ;org-roam hardcodes target file logic
         :org-roam (:if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n"))
         :unnarrowed t)))
```

**Comment by spacekitteh** [comment]
Ah, cheers!

**Comment by spacekitteh** [comment]
Actually no, that doesn't work, as org-roam freaks out if there's *anything* in the position where `doct--target` puts the target. I think the best solution to this is either to get rid of the hard-coding (and only use it as a default), or to write a doct post-conversion hook.

**Comment by spacekitteh** [comment]
Ok, this has been fixed with https://github.com/org-roam/org-roam/pull/1701. It needs a `:function ignore`.

**Comment by vherrmann** [comment]
I've wrote a package for this here: https://gist.github.com/vherrmann/f9b21eeea7d7c9123dc400a30599d50d that should iirc work for org-roamv2
