### ISSUE TITLE
flatten-list

### ISSUE THREAD

**Issue by ndw** [progfolio/doct#2]
I'm not sure when it got introduced, but the latest HEAD includes a call to `flatten-list` which is not defined in Emacs 26.

**Comment by progfolio** [comment]
Thanks again! Will have a patch up momentarily.

**Comment by progfolio** [comment]
@ndw: This should take care of it, but I only have Emacs 28.0.50 available on this machine. Let me know if this works for you:
https://github.com/progfolio/doct/commit/cdb11fc49f5d00dfff9b258d3122e1bb6b1fbd92

Thanks again

**Comment by ndw** [comment]
Yep, that seems to work.

**Comment by progfolio** [comment]
Appreciate it!
