### ISSUE TITLE
Getting DOCT to declare the entries for org-roam

### ISSUE THREAD

**Issue by algon-ns** [progfolio/doct#22]
I'm trying to use DOCT, but I can't figure out how to configure the two entries for org-roam.

I'm not really an expert, so I find the documentation kind of complicated.

med venlig hilsen (=With Kind Regards)
Niels

**Comment by progfolio** [comment]
Hi Niels,

Thanks for trying out doct. org-roam extends the org-capture-template syntax with its own keywords. I've had several people ask about using doct with org-roam. You can try the code in the following gist:

https://gist.github.com/progfolio/2871f12099be3913a1c61a3c3062f4fd

And here is an example of how to use it: https://github.com/progfolio/doct/issues/18#issuecomment-664593854

If you run into any specific problems with that, let me know.
