### ISSUE TITLE
Can I access doct-custom/etc from a :hook function?

### ISSUE THREAD

**Issue by philipsd6** [progfolio/doct#24]
I'm using `:template "my template"`, `:file myfile.org` and `:hook (lambda () (my/capture-func))` as well as `:my-custom-var1`, etc... to enrich the filled template with additional items.

From inside `my/capture-func` how can I:
1. access the buffer opened for `myfile.org`? (Without hardcoding it!)
2. access the custom custom vars on the doct-custom plist?

**Comment by progfolio** [comment]
> access the buffer opened for myfile.org?

The hook function is run in the context of the capture buffer,
which itself is just a narrowed indirect buffer of the target buffer.

> access the custom custom vars on the doct-custom plist?

Here's an example that illustrates how to access doct's custom metadata plist from 
a hook function via the `doct-get` fucntion:

```emacs-lisp
(progn
  (require 'org-capture)
  (let ((org-capture-templates
          (doct '("access doct custom plist from hook" :keys "a"
                  :type plain
                  :file "/tmp/test.org"
                  :template "foo"
                  :foo "bar"
                  :hook (lambda ()
                          (goto-char (point-max))
                          (insert (doct-get :foo 'local)))))))
    (org-capture nil "a")))
```

The hook fucntion will move point to the end of the capture buffer
and insert the `:foo`'s value from doct's `:custom` metadata plist.

The result should be the string "foobar".

Does that help?

**Comment by philipsd6** [comment]
Yes, that very much does help! Thank you!

Basically what I'm doing is logging meeting topics throughout the week in a top level heading, then on meeting day, I start a new capture that moves those topics to the current entry as checkboxes, and I need the `doct-get` to grab the meeting context so I can move the right set of meeting topics.

**Comment by progfolio** [comment]
You're welcome.
If you are able to make the template generic enough, please consider sharing it.
I have a collection of capture templates I'm organizing that I plan on publishing soon.
Sounds like a useful workflow.

**Comment by philipsd6** [comment]
Here you go... not sure where else to share it! 

My workflow for this is:
1. Any time I have an idea to discuss in an upcoming Admin or Team meeting, I can press <kbd>Ctrl-c</kbd> <kbd>c</kbd> <kbd>m</kbd> <kbd>t</kbd> <kbd>t</kbd> or <kbd>a</kbd> to capture the topic and get right back to where I was working.
2. Then, when a meeting rolls around, then I can press <kbd>Ctrl-c</kbd> <kbd>c</kbd> <kbd>m</kbd> <kbd>m</kbd> <kbd>t</kbd> or <kbd>a</kbd> to start capturing meeting notes. The capture buffer will be pre-filled with:
   * a heading for the meeting context, with `[0/0]` only if there are topics found for this meeting to summary covered topics.
   * a list of the expected attendees. I can delete any who are not present.
   * a checkbox list of the topics to discuss, if any. 
   * a starting point for taking notes.

The only things I'm unhappy about is that I can't seem to use the template `:description` for the `:olp` and title instead of my custom `:context` property. It seems redundant! 

```elisp
(setq my/top-heading "Meeting Topics")

(defun my/get-attendees ()
  "Get the default attendees from the doct-custom property list as a list of checkboxes"
  (mapconcat (lambda (x) (format "- %s" x))
             (split-string (doct-get :attendees) "," t)
             "\n"))

(defun my/take-topics ()
  "Cut the current topics from the :context of the top-heading as a list of checkboxes"
  (save-excursion
    (save-restriction
      (widen)
      (ignore-errors
        (goto-char (org-find-olp `(,my/top-heading ,(doct-get :context 'local)) 't))
        (let* ((elt (org-element-at-point))
               (beg (org-element-property :contents-begin elt))
               (end (org-element-property :contents-end elt))
               (topics (split-string (buffer-substring-no-properties beg end) "\n" t)))
          (progn
            (delete-region beg end)
            (mapconcat (lambda (x) (if (string-prefix-p "- " x)
                                       (format "- [ ] %s" (substring x 2))
                                     x))
                       topics
                       "\n")))))))

(setq org-capture-templates
      (doct
       `(("Meeting" :keys "m"
          :file "work.org"
          :children (("Topic" :keys "t"
                      :type item
                      :immediate-finish t
                      :template "%^{Description}"
                      :children (("Admin" :keys "a" :context "Admin"
                                  :olp (,my/top-heading "Admin"))
                                 ("Team" :keys "t" :context "Team"
                                  :olp (,my/top-heading "Team"))
                                 ))
                     ("Start Meeting" :keys "m"
                      :type entry
                      :datetree t
                      :tree-type week
                      :jump-to-captured t
                      :template ("* %{context} Meeting :meeting:"
                                 ":PROPERTIES:"
                                 ":Created: %T"
                                 ":From: %a"
                                 ":END:"
                                 "*Attendees:*"
                                 "%(my/get-attendees)"
                                 ""
                                 "*Notes:*"
                                 "- %?")
                      :hook (lambda ()
                              (let ((topics (my/take-topics)))
                                (if topics
                                    (save-excursion
                                      (search-backward "\n*Notes:*")
                                      (insert "\n*Topics:*\n"
                                              topics
                                              "\n")))))
                      :empty-lines: 1
                      :clock-in t
                      :children (("Admin" :keys "a"
                                  :context "Admin"
                                  :attendees "Manager A")
                                 ("Team" :keys "t"
                                  :context "Team"
                                  :attendees "Alice,Bob,Charlie"))
                      ))
          ))))
```
