### ISSUE TITLE
how about to set tag?

### ISSUE THREAD

**Issue by ghost** [progfolio/doct#25]
Some distro like Debian or GNU Guix prefer to add to their repository only "completed" software, where authors set tag in order to say "our software is ready to stable use". How about to set tag someday?

**Comment by progfolio** [comment]
I don't necessarily agree with that idea. Software is rarely complete. I never aim to introduce bugs, so I have little way (outside of testing) of knowing when a particular commit is "stable". By tagging releases as stable, I'm encouraging users to lock in to a version which may have bugs or may be improved.

The package is also published on MELPA, which upon tagging, will be uploaded to MELPA "stable" which encourages similar lock in. See the discussion here for why that is misleading for users:

https://github.com/melpa/melpa/issues/6656

I feel the real solution is to empower users to define their own releases via their package manager. 

https://www.github.com/raxod502/straight.el 
accomplishes this through lock files. It appears that guix allows one to specify a commit as well as a tag, too. With these, a user can provide their own version of stability and easily upgrade/rollback when desired.

**Comment by ghost** [comment]
Ok, thank you for answer.
