### ISSUE TITLE
Org 9.5 capture refile-targets

### ISSUE THREAD

**Issue by tpeacock19** [progfolio/doct#29]
With the release of org 9.5 there is an option to define refile targets when exiting capture mode with `org-capture-refile`. It takes the same format as `org-refile-targets` and uses the `:refile-targets` property in the capture template. I was able to get it to work adding the property to `doct-option-keywords`. I just wanted to bring to your attention.

**Comment by progfolio** [comment]
I had a note about that, but forgot all about it. Thanks for the reminder. Should be accounted for now.
