### ISSUE TITLE
I am lossing the underscore

### ISSUE THREAD

**Issue by Ypot** [progfolio/doct#39]
## Describe the problem
When I use `_` before the ‘%\N’ (the text entered at the Nth ‘%^{PROMPT}’) the `_` dissapears.

## Directions to reproduce

```
(setopt org-capture-templates
  (doct-add-to org-capture-templates
               `("Project" :keys "j"
                 :type entry
                 :id "2024"
                 :prepend t
                 :immediate-finish t
                 :jump-to-captured t
                 :hook
                 ,(defun +org-capture-captialize-dir-prop ()
                    (save-excursion
                      (goto-char (point-min))
                      (when (re-search-forward "^:DIR:" nil t)
                        (upcase-region (line-beginning-position) (line-end-position)))))
                 :template ("* PROJ %^{1 CLIENT}-_%^{2 OT}_
$Contract_%\\2 := 10000 EUR$))))
```

Instead of "Contract_2 OT" it writes down "Contract2 OT", the `_` is missing.

### Version information

* Emacs version:  29.3
* Org mode version:  9.8-pre
* Operating system: Win

**Comment by progfolio** [comment]
I'm unable to reproduce on my end.
Doss the issue occur if you evaluate the following in your scratch buffer?

```emacs-lisp
(progn
  (require 'org-capture)
  (let ((org-capture-templates
         '(("t" "test" entry (file "")
          "* %^{1 client}-%^{2 ot}\n$Contract_%\\2"
         :immediate-finish t
         :jump-to-captured t)))) 
    (org-capture nil "t"))) 
```

Note your example is missing a backslash before the "2".  elisp interprets a single backslash as an escape character in a string literal.
"\2" vs "\\\2".

**Comment by progfolio** [comment]
I'll consider this closed for now. Feel free to comment if you're still having the issue and you are sure it's related to doct. Thanks.
