### ISSUE TITLE
Support `(file "path/to/template.org")` template paths

### ISSUE THREAD

**Issue by swflint** [progfolio/doct#6]
Org natively allows the use of files for storing templates.  Support for this would make using doct easier.

**Comment by progfolio** [comment]
This is what the `:template-file` keyword allows.
https://github.com/progfolio/doct#template

I should probably add an explicit example to the docs to make that clearer.

```emacs-lisp
(doct '(("Template file" :keys "t" :file "" :template-file "path/to/template.txt")))
```
Are you suggesting that the `:template` keyword accept the vanilla syntax list like so?:
```emacs-lisp
(doct '(("Template file" :keys "t" :file "" :template (file "path/to/template.txt"))))
```

**Comment by progfolio** [comment]
@swflint I've added an example for the `:template-file` keyword to the documentation.
Let me know if this addresses your suggestion or if I misinterpreted it.

Thank you

**Comment by swflint** [comment]
That's it.  Thanks.
