### ISSUE TITLE
warnings issued with example doct.

### ISSUE THREAD

**Issue by mohkale** [progfolio/doct#8]
## Describe the problem
In the README, there's an example doct:

```elisp
(doct '(("Parent" :keys "p"
         :file "~/example.org"
         :prepend t
         :template ("* %doct(todo-state) %^{Description}"
                    ":PROPERTIES:"
                    ":Created: %U"
                    ":END:"
                    "%?")
         :children (("First Child"  :keys "1"
                     :headline   "One"
                     :todo-state "TODO"
                     :hook (lambda () (message "\"First Child\" selected.")))
                    ("Second Child" :keys "2"
                     :headline   "Two"
                     :todo-state "NEXT")
                    ("Third Child"  :keys "3"
                     :headline   "Three"
                     :todo-state "MAYBE")))))
```

If I try to evaluate it I get a tonne of warnings.

## Directions to reproduce

1. Copy the example doct to your `*scratch*` buffer.
2. evaluate your scratch buffer (using `eval-buffer`).

When I do so, the warnings buffer pops up with the following messages.

```elisp
Warning (doct): :template %?
:END:
:Created: %U
:PROPERTIES:
* TODO %^{Description} in declaration:
(First Child :keys p1 :headline One :todo-state TODO :hook (lambda nil (message "First Child" selected.)) :file ~/example.org :prepend t :template (* %doct(todo-state) %^{Description} :PROPERTIES: :Created: %U :END: %?))
is not a valid Org entry
Are you missing the leading ’*’?
Warning (doct): :template %?
:END:
:Created: %U
:PROPERTIES:
* NEXT %^{Description} in declaration:
(Second Child :keys p2 :headline Two :todo-state NEXT :file ~/example.org :prepend t :template (* %doct(todo-state) %^{Description} :PROPERTIES: :Created: %U :END: %?))
is not a valid Org entry
Are you missing the leading ’*’?
Warning (doct): :template %?
:END:
:Created: %U
:PROPERTIES:
* MAYBE %^{Description} in declaration:
(Third Child :keys p3 :headline Three :todo-state MAYBE :file ~/example.org :prepend t :template (* %doct(todo-state) %^{Description} :PROPERTIES: :Created: %U :END: %?))
is not a valid Org entry
Are you missing the leading ’*’?
```

### Version information

* Emacs version: GNU Emacs 27.0.60 (build 1, x86_64-w64-mingw32) of 2019-12-28
* Org mode version: Org mode version 9.3.6 (9.3.6-elpa @ c:/Users/MoHKale/.emacs.d/bin/elpa/org-9.3.6/)
* Operating system: Windows 10

**Comment by mohkale** [comment]
I'm having the same issue with all of my own templates as well.

**Comment by progfolio** [comment]
Sorry! Working on a patch now!

**Comment by mohkale** [comment]
No probs, issues like this are inevitable with a package this cool 😎.

**Comment by progfolio** [comment]
Temporary solution:
``` emacs-lisp
(setq doct-warn-when-unbound nil)
```
Will disable all warnings. (Note to self: rename that variable)

**Comment by mohkale** [comment]
Yeah, I encountered that variable when trying to make doct quieter, but I didn't try it cause the name seemed to imply it was only for a single type of issue. Maybe name it `doct-allow-warnings` or something.

**Comment by progfolio** [comment]
That branch above fixes the example you gave.
Would you mind testing it on your templates?

**Comment by mohkale** [comment]
Yep, everythings working again. Thnx for the great work 😄.

**Comment by progfolio** [comment]
Excellent. Will merge to master once I do some more cleanup!

**Comment by mohkale** [comment]
Kay, I'll close this issue for now. 😎.
